### ISSUE TITLE
The system doesn't work

### ISSUE THREAD

**Issue by NLPZSQ** [diffbot/knowledge-net#5]
After following the README file, it still won't run.
It always fails to download the model.

**Comment by schmidek** [comment]
What step exactly didn't work?

You should be able to use the pretrained model by:

1. downloading the release https://github.com/diffbot/knowledge-net/releases/download/EMNLP2019/knowledge-net-EMNLP2019.zip and extracting it
2. Create a virtual env `python3.7 -m venv knowledgenet` `source knowledgenet/bin/activate`
3. `cd knowledge-net-EMNLP2019/baselines/EMNLP2019`
4. `pip install -r requirements.txt`
5. `python -m spacy download en_core_web_lg` I have had this timeout, but just running it again should work
6. `echo "Butler W. Lampson (born December 23, 1943) is an American computer scientist contributing to the development and implementation of distributed, personal computing. He is a Technical Fellow at Microsoft and an Adjunct Professor at MIT." | python run.py`
